Change

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -22,7 +22,6 @@ jobs:
       contents: read  # Прочтение репозитория
       id-token: write  # Разрешение для получения и использования ID токенов
 
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -99,10 +98,14 @@ jobs:
           pattern: allure-results-${{ github.event.inputs.deployment_target }}
           merge-multiple: true
 
+      # Убедимся, что директория _site существует
+      - name: Ensure _site directory exists
+        run: mkdir -p _site
+
       # Генерация отчета Allure
       - name: Generate Allure Report
         run: |
-          allure generate -c allure-results -o _site
+          allure generate -c allure-results -o _site || (echo "Allure report generation failed" && exit 1)
 
       # Хранение сгенерированного отчета
       - name: Store generated report
@@ -128,7 +131,7 @@ jobs:
       - name: List files in the downloaded artifact
         run: |
           echo "Listing files in _site"
-          ls -R _site || echo "_site not found"  # Проверка наличия артефакта
+          ls -R _site || echo "_site directory not found"  # Проверка наличия артефакта
 
       - name: Upload Pages artifact
         uses: actions/upload-artifact@v4  # Явное указание на v4 для upload-artifact
@@ -138,4 +141,4 @@ jobs:
 
       - name: Deploy to GitHub Pages
         id: deployment
-        uses: actions/deploy-pages@v2  # Для деплоя используем deploy-pages@v2
+        uses: actions/deploy-pages@v4  # Для деплоя используем deploy-pages@v4
